### ISSUE TITLE
On an Ubuntu 18.0  with a small test project get the following comple errors:

### ISSUE THREAD

**Issue by WhatMeWorry** [BindBC/bindbc-freeimage#1]
cat dub.sdl
name "kyle"
description "A minimal D application."
authors "generic"
copyright "Copyright © 2019, generic"
license "proprietary"

dependency "bindbc-freeimage" version="~>0.1.0"
versions "FI_318"

================================================================

cat source/app.d
import std.stdio;
import bindbc.freeimage;

import bindbc.loader.sharedlib

/* Import the sharedlib module for error handling. Assigning an alias
 ensures the function names do not conflict with other public APIs
 and makes it obvious that the functions belong to the loader rather
 than bindbc.sdl. */

import loader = bindbc.loader.sharedlib;

void main()
{
	writeln("Edit source/app.d to start your project.");
	FISupport ret = loadFreeImage();
}

================================================================
(I tried throwing in the "import loader = bindbc.loader.sharedlib;" thinking that might resolve
the SharedLib compile time errors below) 

dub build --compiler=ldc2

Performing "debug" build using ldc2 for x86_64.
bindbc-loader 0.1.1: target for configuration "noBC" is up to date.
bindbc-freeimage 0.1.0: building configuration "dynamic"...
../../../.dub/packages/bindbc-freeimage-0.1.0/bindbc-freeimage/source/bindbc/freeimage/binddynamic.d(638,8): Error: no property bindSymbol_stdcall for type SharedLib
../../../.dub/packages/bindbc-freeimage-0.1.0/bindbc-freeimage/source/bindbc/freeimage/binddynamic.d(639,8): Error: no property bindSymbol_stdcall for type SharedLib
../../../.dub/packages/bindbc-freeimage-0.1.0/bindbc-freeimage/source/bindbc/freeimage/binddynamic.d(640,8): Error: no property bindSymbol_stdcall for type SharedLib
(more deleted for brevity)

**Comment by mdparker** [comment]
I've got the wrong version of `bindbc-loader` configured as a dependency, so it's using the one already on your system. Do a `dub upgrade` to get the latest version and the error should go away. I'll update the `dub.sdl` here and push out a new release in a bit.

**Comment by WhatMeWorry** [comment]
Thanks!  compiles fine.  In the "The dynamic binding" section in the code block you have the below commented out.  Was this something that wasn't cleaned up. Or should we use loadFreeImage("libs/freeimage.dll") on Windows in place of "FISupport ret = loadFreeImage();"

Great job with bindbc by the way.

/*
This version attempts to load the FreeImage library using a user-supplied file name.
Usually, the name and/or path used will be platform specific, as in this example
which attempts to load `freeimage.dll` from the `libs` subdirectory, relative
to the executable, only on Windows.
*/
// version(Windows) loadFreeImage("libs/freeimage.dll")

**Comment by mdparker** [comment]
It's just an example. By default, the no-arg version of the loader attempts to load the shared library using file names commonly found in the wild. If you need to use a non-standard file name, or load the shared library from a location that's not on the system's library search path, then this is how you would do it. For example, some Windows apps are shipped with their DLLs in a subdirectory. In that case, it won't be on the system's library search path so you'd want to load it as in the example.
